### ISSUE TITLE
Fails to load integration

### ISSUE THREAD

**Issue by kalaws** [faanskit/ha-checkwatt#61]
integration stopped working, and I’m guessing it might be related to today’s update of Core.  

Logger: custom_components.checkwatt
Source: helpers/update_coordinator.py:300
Integration: CheckWatt ([documentation](https://github.com/faanskit/ha-checkwatt#readme), [issues](https://github.com/faanskit/ha-checkwatt/issues))
First occurred: 18:06:32 (74 occurrences)
Last logged: 19:00:48

Unexpected error fetching checkwatt data: 'CheckwattManager' object has no attribute 'fcrd_percentage'
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/checkwatt/__init__.py", line 225, in _async_update_data
    "fcr_d_state": cw_inst.fcrd_percentage,
                   ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CheckwattManager' object has no attribute 'fcrd_percentage'
```

**Comment by kalaws** [comment]
Complete reinstall of integration solved the issue.
